version: "3"
services:
  auth-web:
    build: docker/nginx
    ports:
      - 127.0.0.1:8000:80
    volumes:
       - ./:/app/:cached

  auth-backend:
    build: .
    volumes:
       - ./:/app/:cached

  auth-worker:
    build: .
    volumes:
       - ./:/app/:cached
    command: ['./bin/hello-worker']

  redis:
    image: redis:5.0-alpine
    volumes:
      - ./redis-data:/data

volumes:
  rabbitmq-data:
